# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0003_auto_20161229_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('position', models.TextField(max_length=255, verbose_name='Position')),
            ],
        ),
    ]
