# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0004_auto_20161229_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='office',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='rip_app.OfficesModel'),
            preserve_default=False,
        ),
    ]
