# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-29 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0005_membersmodel_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membersmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
