# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0006_auto_20161229_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesmodel',
            name='info',
            field=models.TextField(default=1, max_length=255, verbose_name='info'),
            preserve_default=False,
        ),
    ]
