# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0007_officesmodel_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officesmodel',
            name='info',
        ),
    ]
