# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-30 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0008_remove_officesmodel_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='officesmodel',
            name='info',
            field=models.TextField(null=True),
        ),
    ]
