# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0010_auto_20170102_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='picture',
            field=models.TextField(null=True),
        ),
    ]
