# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0011_auto_20170102_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='location',
            field=models.TextField(max_length=255, verbose_name='Расположение'),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='named',
            field=models.CharField(max_length=30, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='officesmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='', verbose_name=''),
        ),
    ]
