# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-03 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0012_auto_20170102_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officesmodel',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
    ]
