# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0014_remove_officesmodel_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membersmodel',
            name='office',
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='office',
            field=models.ManyToManyField(related_name='members', to='rip_app.OfficesModel'),
        ),
    ]
