# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rip_app', '0015_auto_20170106_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='membersmodel',
            name='password',
            field=models.CharField(default='12345', max_length=255),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='membersmodel',
            name='username',
            field=models.CharField(default='login', max_length=255),
        ),
    ]
